-- NEEDS PROPER FORMATTING!!

Hot sauce (name, description, location, sco_score)
    ('Elijahs Xtreme Regret Hot Sauce', 'Delicious combination of extreme heat and fruity sweetness. There’s more depth here than many super-hot sauces and very little dilution keeping you from the Carolina Reaper and scorpion pepper’s super-spiciness and natural sweetness.', 'Lowell, NC', 'Killer')
    ('Blairs Ultra Death Sauce', 'Blair’s Ultra Death Sauce walks the talk of its name. This is extreme heat, so use caution with it. This sauce has some sweet flavor behind the heat…but who are we kidding, it’s all about the spiciness and wicked packaging here.', 'Highlands, NJ', 'Killer')
    ('Burn After Eating Hot Sauce', 'It’s surprisingly tasty, but it’s not for the timid. The little amount that most users will use won’t showcase how delicious the sauce is.', 'Rochester, NY', 'Killer')
    ('Satans Blood Hot Sauce', 'The overwhelming heat is the experience, so use sparingly. Those looking for a balance of flavor and spiciness should look elsewhere.', 'Riveria Beach, FL', 'Killer')
    ('Grinders Death Nectar', 'There’s a hint of citrus behind the heat, but truly the spiciness is the star. Use with caution.', 'Kansas City, MO', 'Killer')
    ('Aka Miso Ghost-Reaper Hot Sauce', 'Few hot sauces nail the flavor and heat combo as well as Aka Miso Ghost-Reaper. It’s an “umami bomb” — full of bold flavors and a heat that stacks up well against it.','Huston, TX', 'Extreme')
    ('Professor Phardtpounder’s Colon Cleaner Hot Sauce', 'Flavorful, mustard-based hot sauce with nicely balanced heat. It’s very collectible and makes a statement on the table.', 'Riveria Beach, FL', 'Extreme')
    ('Torchbearer Garlic Reaper Sauce', 'Bold heat, but with a bold flavor to match.', 'Mechanicsburg, PA', 'Extreme'),
    ('Torchbearer Zombie Apocalypse Hot Sauce', 'It’s a big heat, but it’s done with natural peppers (ghost pepper and habanero) so it’s packed with natural fiery sweetness.', 'Mechanicsburg, PA', 'Extreme')
    ('Da Bomb Beyond Insanity Hot Sauce', 'Very collectible packaging meets big heat that tends to linger. Careful - too much will overtake your meal. Smoky and sweet - but use a drop or two at a time!', 'Kansas City, KS', 'Extreme')
    ('Slap Ya Mama Cajun Pepper Sauce', 'Well-balanced Louisiana-style hot sauce, with more heat and flavor than a lot of competitors.', 'Ville Platte, LA', 'Hot')
    ('Purple Haze Hot Sauce', 'A sweet ride with its mix of pineapple, apple cider vinegar, red cabbage, habanero peppers, and more.', 'Woodstock, NY', 'Hot')
    ('African Dream Foods Ghost Peri-Peri Sauce', 'deliciously well-balanced sweet and tangy hot sauce with a bold, but eatable heat.', 'Vancouver, WA', 'Hot')
    ('Pain 100% Hot Sauce', 'Surprisingly well-balanced hot sauce for all the claims of total torture on the label.', 'Kansas City, KS', 'Hot')
    ('Dat’l Hook Ya Datil Pepper Sauce', 'Pairs big earthy flavor with bold spices and a very eatable heat.', 'St. Augustine, FL', 'Hot')
    ('Hot Ones "The Classic" Hot Sauce.', 'Tangy, nutty, earthy, and a touch smoky with a very eatable heat.', 'Fort Mill, SC', 'Mild')
    ('Hoppin Hot Sauce', 'Pure California feel-good flavor magic, mixing Meyer lemons, puya peppers, chipotle meco, and spices perfectly.', 'San Jose, CA', 'Mild')
    ('The Bronx Greenmarket Hot Sauce', 'Delicious mix of earthy, sweet, and tangy with a low-medium heat.', 'New York City, NY', 'Mild')
    ('Melindas Black Truffle Hot Sauce', 'Has a nice flavor twist, using Parmesan, garlic, and honey to deliver some depth to the flavor beyond those delicious truffles.', 'Irving, TX', 'Mild')
    ('Queen Majesty Scotch Bonnet & Ginger Hot Sauce', 'The fruity sweetness of the pepper pairs well with ginger. Unique exotic flavor and label.', 'Queens, NY', 'Mild')

Users (name, user_name, email, password)
    (Alyssa, AlyssaHotShot, pepper1@hotshot.com, '1234')
    (Hector, HectorHotShot, pepper2@hotshot.com, '1234')
    (Josh, JoshHotShot, pepper3@hotshot.com, '1234')
    (Josiah, JosiahHotShot, pepper4@hotshot.com, '1234')